version: "3.8"
services:
  app:
    build: ./app
    depends_on:
      - db
    environment: 
      CONFIG_DB_USER: root
      CONFIG_DB_PASS: opsta
      CONFIG_DB_HOST: 'db'
      CONFIG_DB_PORT: '3306'
      CONFIG_DB_NAME: knights
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: opsta
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
