version: "3.8"
services:

  app:
    build: ./app
    environment: 
      MYSQL_USER: root
      MYSQL_PASSWORD: opsta
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
      MYSQL_DATABASE: knights
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: opsta
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
