version: "3.8"

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.29.2
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    container_name: dashboard
    image: grafana/grafana:8.1.2
    volumes:
      - ./grafana/provisioning/dashboard:/etc/grafana/provisioning/dashboard
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      retries: 30
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.40.0
    container_name: cadvisor
    ports: 
      - "8080:8080"
    privileged: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: false
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker/
        target: /var/lib/docker
        read_only: true
      - type: bind
        source: /dev/disk/
        target: /dev/disk
        read_only: true
    networks: 
      - monitoring

  nodeexporter:
    image: quay.io/prometheus/node-exporter:v1.2.2
    container_name: nodeexporter
    pid: host
    ports:
      - '9100:9100'
    volumes:
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
      - type: bind
        source: /
        target: /host
        read_only: true
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - monitoring

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.23.0
    container_name: alertmanager
    ports: 
      - "9093:9093"
    volumes:
      - type: bind
        source: ./alertmanager/alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
      - type: bind
        source: /alertmanager
        target: /alertmanager
        read_only: false
    networks:
      - monitoring

networks:
  monitoring:
