version: "3.8"
services: 
  proxy:
    container_name: nginx
    image: nginx:1.21-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks: 
      - kitty
  hello:
    container_name: hello
    image: dukecyber/http-go:v1.0-simple
    ports:
      - "9000:9000"
    networks: 
      - kitty
networks:
  kitty: