version: "3.8"
services:
  hello-1:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3


  hello-2:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "8002:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  nginx:
    image: nginx:latest
    command: /bin/bash -c "rm -rf /docker-entrypoint.d/* && nginx -g 'daemon off;'"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"