---
global:
  scrape_interval: 5s
  scrape_timeout: 3s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs: []